Include headers needed to compile with GCC 15's -std=gnu23 default
```
In file included from ../piper-vamp-cpp/vamp-json/VampJson.h:55,
                 from ../piper-vamp-cpp/vamp-server/convert.cpp:36:
../piper-vamp-cpp/vamp-support/PluginHandleMapper.h:69:13: error: ‘uint32_t’ does not name a type
   69 |     typedef uint32_t Handle;
      |             ^~~~~~~~
../piper-vamp-cpp/vamp-support/PluginHandleMapper.h:39:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
   38 | #include "PluginOutputIdMapper.h"
  +++ |+#include <cstdint>
   39 |

../piper-vamp-cpp/ext/json11/json11.cpp: In function ‘void json11::dump(const std::string&, std::string&)’:
../piper-vamp-cpp/ext/json11/json11.cpp:95:32: error: ‘uint8_t’ does not name a type
   95 |         } else if (static_cast<uint8_t>(ch) <= 0x1f) {
      |                                ^~~~~~~
../piper-vamp-cpp/ext/json11/json11.cpp:25:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
   24 | #include <cmath>
  +++ |+#include <cstdint>
   25 | #include <cstdlib>
```

Signed-off-by: Michel Lind <salimma@fedoraproject.org>